### obtener todas las reservas
GET  http://localhost:3000/bookings
### obtener las reservas por id del recurso
GET  http://localhost:3000/bookings/idresource?idRecurso=773&idTipoR=Auditorio
### obtener las reservas por id del usuario
GET  http://localhost:3000/bookings/iduser/20181020072

### ontener calendario de una reserva
GET  http://localhost:3000/bookings/calendar/1c7b5f90-4800-1dc9-9198-4111463f925c
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTgxMDIwMDcyIiwiaWF0IjoxNzAxMjE1Mzk3LCJleHAiOjE3MDEyMTcxOTd9.q-g33UVwMaC8LiEHg1rP-CiwKttBjZlKRzIqpDlIMqQ
### crear una nueva reserva
POST  http://localhost:3000/bookings
Content-Type: application/json

{
  "idRecurso": "655",
  "idTipoR": "Laboratorio",
  "idUsuario": "20181020072",
  "idEstado": "activo",
  "calendarios": [
    {
      "fechaInicio":"2023-11-22 10:00:00",
      "fechaFin": "2023-11-22 12:00:00"
    },
    {
      "fechaInicio":"2023-11-22 14:00:00",
      "fechaFin": "2023-11-22 16:00:00"
    }
  ]
}

### crear segunda reserva
POST  http://localhost:3000/bookings
Content-Type: application/json

{
  "idRecurso": "655",
  "idTipoR": "Laboratorio",
  "idUsuario": "20181020072",
  "idEstado": "activo",
  "calendarios": [
    {
      "fechaInicio":"2023-11-23 10:00:00",
      "fechaFin": "2023-11-23 12:00:00"
    },
    {
      "fechaInicio":"2023-11-23 14:00:00",
      "fechaFin": "2023-11-23 16:00:00"
    }
  ]
}

### prueba cruce reserva
POST  http://localhost:3000/bookings
Content-Type: application/json

{
  "idRecurso": "655",
  "idTipoR": "Laboratorio",
  "idUsuario": "20181020072",
  "idEstado": "activo",
  "calendarios": [
    {
      "fechaInicio":"2023-11-23 10:00:00",
      "fechaFin": "2023-11-23 12:00:00"
    },
    {
      "fechaInicio":"2023-11-23 14:00:00",
      "fechaFin": "2023-11-23 16:00:00"
    }
  ]
}

### prueba formato reserva

POST  http://localhost:3000/bookings
Content-Type: application/json

{
  "idRecurso": "773",
  "idTipoR": "Auditorio",
  "idUsuario": "20181020072",
  "idEstado": "activo",
  "calendarios": [
    {
      "fechaInicio":"2023-11-23 10:00:00",
      "fechaFin": "2023-11-23 12:00:00"
    },
    {
      "fechaInicio":"2023-11-23 14:00:00",
      "fechaFin": "2023-11-23 16:00:00"
    }
  ]
}

### obtener  reserva por usuario y estado 

GET  http://localhost:3000/bookings/userstate?idUsuario=20181020072&idEstado=activo
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTgxMDIwMDcyIiwiaWF0IjoxNzAxMjAwNjk5LCJleHAiOjE3MDEyMDI0OTl9.ybhAvRSNZY45tOnZ1giwjC70I_nzCKpiRqqD8msOYtU
