### obtener todas las reservas
GET  http://localhost:3000/bookings
### obtener las reservas por id del recurso
GET  http://localhost:3000/bookings/idresource?idRecurso=386&idTipoR=Auditorio
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTgxMDIwMDcyIiwiaWF0IjoxNzAxMjM5NTkyLCJleHAiOjE3MDEyNDEzOTJ9.Z529EAof0hku0xJgio06Euwp4tT9GSwT_kV38v57XUI
### obtener las reservas por id del usuario
GET  http://localhost:3000/bookings/iduser/20181020072

### ontener calendario de una reserva
GET  http://localhost:3000/bookings/calendar/1c7b5f90-4800-1dc9-9198-4111463f925c
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTgxMDIwMDcyIiwiaWF0IjoxNzAxMjE1Mzk3LCJleHAiOjE3MDEyMTcxOTd9.q-g33UVwMaC8LiEHg1rP-CiwKttBjZlKRzIqpDlIMqQ
### crear una nueva reserva
POST  http://localhost:3000/bookings
Content-Type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTgxMDIwMDcyIiwiaWF0IjoxNzAxMjM5NTkyLCJleHAiOjE3MDEyNDEzOTJ9.Z529EAof0hku0xJgio06Euwp4tT9GSwT_kV38v57XUI

{
  "idRecurso": "386",
  "idTipoR": "Auditorio",
  "idUsuario": "20181020064",
  "idEstado": "activo",
  "calendarios": [
    {
      "fechaInicio":"2024-01-15 12:00:00",
      "fechaFin": "2024-01-15 14:00:00"
    }
  ]
}

### crear segunda reserva
POST  http://localhost:3000/bookings
Content-Type: application/json

{
  "idRecurso": "655",
  "idTipoR": "Laboratorio",
  "idUsuario": "20181020072",
  "idEstado": "activo",
  "calendarios": [
    {
      "fechaInicio":"2023-11-23 10:00:00",
      "fechaFin": "2023-11-23 12:00:00"
    },
    {
      "fechaInicio":"2023-11-23 14:00:00",
      "fechaFin": "2023-11-23 16:00:00"
    }
  ]
}

### prueba cruce reserva
POST  http://localhost:3000/bookings
Content-Type: application/json

{
  "idRecurso": "655",
  "idTipoR": "Laboratorio",
  "idUsuario": "20181020072",
  "idEstado": "activo",
  "calendarios": [
    {
      "fechaInicio":"2023-11-23 10:00:00",
      "fechaFin": "2023-11-23 12:00:00"
    },
    {
      "fechaInicio":"2023-11-23 14:00:00",
      "fechaFin": "2023-11-23 16:00:00"
    }
  ]
}

### prueba formato reserva

POST  http://localhost:3000/bookings
Content-Type: application/json

{
  "idRecurso": "773",
  "idTipoR": "Auditorio",
  "idUsuario": "20181020072",
  "idEstado": "activo",
  "calendarios": [
    {
      "fechaInicio":"2023-11-23 10:00:00",
      "fechaFin": "2023-11-23 12:00:00"
    },
    {
      "fechaInicio":"2023-11-23 14:00:00",
      "fechaFin": "2023-11-23 16:00:00"
    }
  ]
}

### obtener  reserva por usuario y estado 

GET  http://localhost:3000/bookings/userstate?idUsuario=20181020072&idEstado=activo
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTgxMDIwMDcyIiwiaWF0IjoxNzAxMjAwNjk5LCJleHAiOjE3MDEyMDI0OTl9.ybhAvRSNZY45tOnZ1giwjC70I_nzCKpiRqqD8msOYtU

### cancelar reserva
PATCH   http://localhost:3000/bookings/updatestate
Content-Type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTgxMDIwMDcyIiwiaWF0IjoxNzAxMjI5NTk1LCJleHAiOjE3MDEyMzEzOTV9.Q0emWaBfLcs_3QEyCRFqQC_Cy_ElQV5LccJwGTuqozY

{
  "idReserva": "bbdea870-4667-1dc9-9198-4111463f925c",
  "idEstado": "cancelado"
}

### Delete reserva
DELETE  http://localhost:3000/bookings/deletebooking
Content-Type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTgxMDIwMDcyIiwiaWF0IjoxNzAxMjMxNzgxLCJleHAiOjE3MDEyMzM1ODF9.wJZntdyeJfO7bjkXjlsmnBzCZ8AyVFjD14N5j4sS7cU

{
  "idReserva": "74b5ff00-e0a6-1dc9-b76f-b18b1acd0910"
}