name: hello_angel

environment:
  sdk: '^3.1.0'


dependencies:
  angel3_container: ^8.0.0
  angel3_framework: ^8.0.0
  angel3_jael: ^8.0.0
  angel3_static: ^8.0.0
  belatuk_pretty_logging: ^6.0.0
  file: ^7.0.0
  logging: ^1.2.0

dev_dependencies:
  angel3_hot: ^8.0.0
