name: hello_angel

environment:
  sdk: '^3.1.0'


dependencies:
  angel3_auth: ^8.0.0
  angel3_container: ^8.0.0
  angel3_cors: ^8.0.0
  angel3_framework: ^8.0.0
  angel3_production: ^8.0.0
  angel3_validate: ^8.0.2
  belatuk_pretty_logging: ^6.0.0
  dart_jsonwebtoken: ^2.12.1
  file: ^7.0.0
  logging: ^1.2.0
  postgres: ^2.6.3
  timezone: ^0.9.2
  uuid: ^4.2.1

dev_dependencies:
  angel3_hot: ^8.0.0
  angel3_serialize_generator: ^8.1.0
  build_runner: ^2.4.6
